[package]
name = "rustorcli"
version = "0.1.0"
authors = ["ainzzorl <ainzzorl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
daemonize = "0.4.1"
nix = "0.17.0"
sysinfo = "0.13.1"
